//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio_Erick.BD_Consultorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int CitaID { get; set; }
        public int PacienteID { get; set; }
        public int DentistaID { get; set; }
        public int MotivoID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int DuracionMinutos { get; set; }
    
        public virtual Dentista Dentista { get; set; }
        public virtual Motivo Motivo { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
