//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Consultorio_Erick.BD_Consultorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Consultorio_Denta_ERICKEntities : DbContext
    {
        public Consultorio_Denta_ERICKEntities()
            : base("name=Consultorio_Denta_ERICKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Dentista> Dentistas { get; set; }
        public virtual DbSet<Motivo> Motivoes { get; set; }
        public virtual DbSet<Paciente> Pacientes { get; set; }
    }
}
